<a href="https://colab.research.google.com/github/vogue20033/FlipClock/blob/master/AI6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
scalar = 2
scalar

2

In [0]:
import numpy as np
import pandas as pd
import scipy

In [9]:
print(np.isscalar(scalar), type(scalar))

True <class 'int'>


In [10]:
[2]

[2]

In [11]:
vector_list = [24,16,45,50]
vector_list

[24, 16, 45, 50]

In [13]:
vector_np = np.array([24,16,45,50])
vector_np

array([24, 16, 45, 50])

In [16]:
vector_reshaped = vector_np.reshape(4,1)
vector_reshaped

array([[24],
       [16],
       [45],
       [50]])

In [15]:
vector_np.shape

(4,)

In [19]:
vector_reshaped.shape

(4, 1)

In [20]:
# Vector Addition
A = vector_np
B = np.array([21])
print(A + B)

[45 37 66 71]


In [21]:
vector_reshaped + B

array([[45],
       [37],
       [66],
       [71]])

In [0]:
# Exercise
A = np.array([21,30,18])
B = np.array([14,19,1])
C = [2]
D = [12,3]

In [23]:
A+B


array([35, 49, 19])

In [24]:
A*B


array([294, 570,  18])

In [25]:
A+C


array([23, 32, 20])

In [26]:
A-C

array([19, 28, 16])

In [27]:
A*C

array([42, 60, 36])

In [28]:
A+D

ValueError: ignored

In [0]:
B_reshaped = B.reshape (3,1)

In [39]:
A * (B_reshaped)

array([[294, 420, 252],
       [399, 570, 342],
       [ 21,  30,  18]])

In [40]:
A_np = np.matrix([[-1, 2],
                 [4, 3]])
A_np

matrix([[-1,  2],
        [ 4,  3]])

In [41]:
B_np = np.matrix([[-7, 4],
                 [4, 0]])
B_np

matrix([[-7,  4],
        [ 4,  0]])

In [44]:
# 3 by 3 matrix
C_np = np.matrix([[3, 0, -5],
                 [9, 8, -2],
                  [5, 0, 8]])
C_np

matrix([[ 3,  0, -5],
        [ 9,  8, -2],
        [ 5,  0,  8]])

In [45]:
 # Matrix Multiplication
  Sum_A_B = A_np * B_np
  Sum_A_B

matrix([[ 15,  -4],
        [-16,  16]])

In [46]:
# Element Wise Multiplication
Elsum_A_B = np.multiply(A_np, B_np)
Elsum_A_B

matrix([[ 7,  8],
        [16,  0]])

In [48]:
# Solving Matrix equation - Fing the inverse of A
A_inverse = np.linalg.inv(A_np)
A_inverse

matrix([[-0.27272727,  0.18181818],
        [ 0.36363636,  0.09090909]])

In [52]:
X = A_inverse * B_np
X

matrix([[ 2.63636364, -1.09090909],
        [-2.18181818,  1.45454545]])

In [53]:
# Using  Scipy to compute
X = np.linalg.solve(A_np, B_np)
X

matrix([[ 2.63636364, -1.09090909],
        [-2.18181818,  1.45454545]])

In [54]:
#find the Determinant
det = np.linalg.det(A_np)
det

-11.000000000000002

In [57]:
# let find the tranpose
transpose = np.transpose(A_np)
transpose

matrix([[-1,  4],
        [ 2,  3]])

In [58]:
transpose = np.transpose(C_np)
transpose

matrix([[ 3,  9,  5],
        [ 0,  8,  0],
        [-5, -2,  8]])

In [59]:
eigvals = np.linalg.eigvals(A_np)
eigvals
# print ("the eng values")

array([-2.46410162,  4.46410162])

In [60]:
eigvals = np.linalg.eigvals(A_np)
print ("the eng values are", eigvals[0], "and", eigvals[1])

the eng values are -2.4641016151377544 and 4.464101615137754


In [61]:
#Ones
X = np.ones((3,3))
X

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
X = np.arange(5)
X

array([0, 1, 2, 3, 4])

In [65]:
y = np.random.rand(4,4)
y

array([[0.64658474, 0.89501141, 0.74385673, 0.34072498],
       [0.75280126, 0.86104827, 0.43383701, 0.85804725],
       [0.57868805, 0.54963776, 0.61205373, 0.33871046],
       [0.19662731, 0.28927882, 0.21071609, 0.89454768]])

In [0]:
#@title Example form fields
#@markdown Forms support many types of fields.

no_type_checking = ''  #@param
string_type = 'example'  #@param {type: "string"}
slider_value = 142  #@param {type: "slider", min: 100, max: 200}
number = 102  #@param {type: "number"}
date = '2010-11-05'  #@param {type: "date"}
pick_me = "monday"  #@param ['monday', 'tuesday', 'wednesday', 'thursday']
select_or_input = "apples" #@param ["apples", "bananas", "oranges"] {allow-input: true}
#@markdown ---
